modLoader="javafml"
loaderVersion="[${minFMLVersion},)"
license="All rights reserved"

[[mods]]
modId="lucky"
version="${modVersion}"
displayName="Lucky Block"
authors="Alex Socha"
description="Adds a block with random outcomes"

[[dependencies.lucky]]
    modId="forge"
    mandatory=true
    versionRange="[${minForgeVersion},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lucky]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minMinecraftVersion},)"
    ordering="NONE"
    side="BOTH"
